POST http://localhost:3000/songs/store
Content-Type: application/json

{
    "title": "bar music",
    "audio_url":"/mypc",
    "image_url":"/mypc",
    "uploader":{
        "uid":"61a6f6ffcffbd20da84dcf1f",
        "name":"Lợi Cao"
    },
    "duration":300
}

###
PUT http://localhost:3000/songs/update
Content-Type: application/json

{
    "title": "test update",
    "_id":"61a744a3e7dcd152b50ffb31",
    "image_url":"mdasdasdasdasdasdadasdypc"
}

###
PUT http://localhost:3000/users/edit
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MWE2ZjZmZmNmZmJkMjBkYTg0ZGNmMWYiLCJkaXNwbGF5X25hbWUiOiJM4bujaSBDYW8iLCJpbWdfdXJsIjoibXlwYy9pbWFnZSIsImlhdCI6MTYzODM1OTAyN30.ckQ_KY6-NhClpuUfuGPebPAeqgGwdbDu7vGepyCsB2U
Content-Type: application/json

{
    "display_name": "test",
    "image_url":"mdasdasdasdasdasdadasdypc"
}

###
Delete http://localhost:3000/songs/delete


###
get http://localhost:3000/songs/user-song?uid=61a6f6ffcffbd20da84dcf1f&page=1


###
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "user_name": "cthanhloi1",
    "password": "123456as"
}

###
POST http://localhost:3000/users/register
Content-Type: application/json

{
    "user_name": "cthanhloi1",
    "password": "123456as",
    "confirm_password": "123456as",
    "display_name":"Lợi Cao",
    "email":"cthanhloi@gmail.com",
    "image_url":"mypc/image"
}


###
POST http://localhost:3000/users/send-mail
Content-Type: application/json

{
    "email":"cthanhloi@gmail.com"
}

###
GET http://localhost:3000/songs/get-Page?page=1

###
GET http://localhost:3000/users/show

###

POST http://localhost:3000/courses/store
Content-Type: application/json

{
    "description": "Lập trình mobile với react native tại f8",
    "name": "công tắc",
    "videoId": "bvZ1_P9eCpw",
    "level": "nhập môn",
    "image": "https://img.youtube.com/"
}